//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.05 at 01:42:14 AM EAT 
//


package com.okworo.soapservice.interfaces;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="booking" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://interfaces.soapservice.okworo.com}client"/>
 *                   &lt;element ref="{http://interfaces.soapservice.okworo.com}room"/>
 *                   &lt;element name="check-in" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="check-out" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="total-price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "booking"
})
@XmlRootElement(name = "bookings")
public class Bookings {

    @XmlElement(required = true)
    protected List<Bookings.Booking> booking;

    /**
     * Gets the value of the booking property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the booking property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooking().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bookings.Booking }
     * 
     * 
     */
    public List<Bookings.Booking> getBooking() {
        if (booking == null) {
            booking = new ArrayList<Bookings.Booking>();
        }
        return this.booking;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://interfaces.soapservice.okworo.com}client"/>
     *         &lt;element ref="{http://interfaces.soapservice.okworo.com}room"/>
     *         &lt;element name="check-in" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="check-out" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="total-price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "client",
        "room",
        "checkIn",
        "checkOut",
        "status",
        "totalPrice"
    })
    public static class Booking {

        @XmlElement(required = true)
        protected Client client;
        @XmlElement(required = true)
        protected Room room;
        @XmlElement(name = "check-in", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkIn;
        @XmlElement(name = "check-out", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkOut;
        @XmlElement(required = true)
        protected String status;
        @XmlElement(name = "total-price", required = true)
        protected BigDecimal totalPrice;

        /**
         * Gets the value of the client property.
         * 
         * @return
         *     possible object is
         *     {@link Client }
         *     
         */
        public Client getClient() {
            return client;
        }

        /**
         * Sets the value of the client property.
         * 
         * @param value
         *     allowed object is
         *     {@link Client }
         *     
         */
        public void setClient(Client value) {
            this.client = value;
        }

        /**
         * Gets the value of the room property.
         * 
         * @return
         *     possible object is
         *     {@link Room }
         *     
         */
        public Room getRoom() {
            return room;
        }

        /**
         * Sets the value of the room property.
         * 
         * @param value
         *     allowed object is
         *     {@link Room }
         *     
         */
        public void setRoom(Room value) {
            this.room = value;
        }

        /**
         * Gets the value of the checkIn property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckIn() {
            return checkIn;
        }

        /**
         * Sets the value of the checkIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckIn(XMLGregorianCalendar value) {
            this.checkIn = value;
        }

        /**
         * Gets the value of the checkOut property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckOut() {
            return checkOut;
        }

        /**
         * Sets the value of the checkOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckOut(XMLGregorianCalendar value) {
            this.checkOut = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the totalPrice property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalPrice() {
            return totalPrice;
        }

        /**
         * Sets the value of the totalPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalPrice(BigDecimal value) {
            this.totalPrice = value;
        }

    }

}
