//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.05 at 03:33:34 PM EAT 
//


package com.okworo.soapservice.interfaces;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.okworo.soapservice.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.okworo.soapservice.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookingRequest }
     * 
     */
    public BookingRequest createBookingRequest() {
        return new BookingRequest();
    }

    /**
     * Create an instance of {@link BookingResponse }
     * 
     */
    public BookingResponse createBookingResponse() {
        return new BookingResponse();
    }

    /**
     * Create an instance of {@link ClientResponse }
     * 
     */
    public ClientResponse createClientResponse() {
        return new ClientResponse();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link RoomResponse }
     * 
     */
    public RoomResponse createRoomResponse() {
        return new RoomResponse();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link ClientByIdRequest }
     * 
     */
    public ClientByIdRequest createClientByIdRequest() {
        return new ClientByIdRequest();
    }

    /**
     * Create an instance of {@link CelsiusToFahrenheitRequest }
     * 
     */
    public CelsiusToFahrenheitRequest createCelsiusToFahrenheitRequest() {
        return new CelsiusToFahrenheitRequest();
    }

    /**
     * Create an instance of {@link AvailableRoomsResponse }
     * 
     */
    public AvailableRoomsResponse createAvailableRoomsResponse() {
        return new AvailableRoomsResponse();
    }

    /**
     * Create an instance of {@link FahrenheitToCelsiusResponse }
     * 
     */
    public FahrenheitToCelsiusResponse createFahrenheitToCelsiusResponse() {
        return new FahrenheitToCelsiusResponse();
    }

    /**
     * Create an instance of {@link RoomByIdRequest }
     * 
     */
    public RoomByIdRequest createRoomByIdRequest() {
        return new RoomByIdRequest();
    }

    /**
     * Create an instance of {@link BookingRequest.Booking }
     * 
     */
    public BookingRequest.Booking createBookingRequestBooking() {
        return new BookingRequest.Booking();
    }

    /**
     * Create an instance of {@link FahrenheitToCelsiusRequest }
     * 
     */
    public FahrenheitToCelsiusRequest createFahrenheitToCelsiusRequest() {
        return new FahrenheitToCelsiusRequest();
    }

    /**
     * Create an instance of {@link BookingConfirmationRequest }
     * 
     */
    public BookingConfirmationRequest createBookingConfirmationRequest() {
        return new BookingConfirmationRequest();
    }

    /**
     * Create an instance of {@link RoomRequest }
     * 
     */
    public RoomRequest createRoomRequest() {
        return new RoomRequest();
    }

    /**
     * Create an instance of {@link BookingResponse.Booking }
     * 
     */
    public BookingResponse.Booking createBookingResponseBooking() {
        return new BookingResponse.Booking();
    }

    /**
     * Create an instance of {@link ClientRequest }
     * 
     */
    public ClientRequest createClientRequest() {
        return new ClientRequest();
    }

    /**
     * Create an instance of {@link AvailableRoomsRequest }
     * 
     */
    public AvailableRoomsRequest createAvailableRoomsRequest() {
        return new AvailableRoomsRequest();
    }

    /**
     * Create an instance of {@link CelsiusToFahrenheitResponse }
     * 
     */
    public CelsiusToFahrenheitResponse createCelsiusToFahrenheitResponse() {
        return new CelsiusToFahrenheitResponse();
    }

}
