//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.05 at 04:38:10 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soapservice.okworo.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.okworo.soapservice.interfaces;
